### ISSUE TITLE
Differences in tick catch-up from game-shell

### ISSUE THREAD

**Issue by MCArth** [fenomas/micro-game-shell#1]
Hi Andy, I've been upgrading my noa version and have been digging into the differences between game-shell and micro-game-shell. One thing I did notice having a visible impact at low frame rates (sub 20), was the game appeared to slow down in a way that wasn't visible with game-shell. Presumably this is because of this line of code:
```
    // never fall more than one tick behind
    shell._lastTick = Math.max(now - tickDur, nextTick)
```
would you be open to allowing the game to play catch-up a bit more? game-shell's approach of allowing aprox 5 ticks of lag (via frameSkip which was defaulted to a tad more than 5* the frame rate) seemed to work well:

```
function tick(shell) {
  var skip = hrtime() + shell.frameSkip
    , pCount = shell._pressCount
    , rCount = shell._releaseCount
    , i, s, t
    , tr = shell._tickRate
    , n = keyNames.length
  while(!shell._paused &&
        hrtime() >= shell._lastTick + tr) {
    
    //Skip frames if we are over budget
    if(hrtime() > skip) {
      shell._lastTick = hrtime() + tr
      return
    }
    
    //Tick the game
    s = hrtime()
    shell.emit("tick")
    t = hrtime()
    shell.tickTime = t - s
    
    //Update counters and time
    ++shell.tickCount
    shell._lastTick += tr
    
    //Shift input state
    for(i=0; i<n; ++i) {
      pCount[i] = rCount[i] = 0
    }
    if(shell._pointerLockActive) {
      shell.prevMouseX = shell.mouseX = shell.width>>1
      shell.prevMouseY = shell.mouseY = shell.height>>1
    } else {
      shell.prevMouseX = shell.mouseX
      shell.prevMouseY = shell.mouseY
    }
    shell.scroll[0] = shell.scroll[1] = shell.scroll[2] = 0
  }
}
```

I could also theorise this approach has some extra cache locality.

As a side note, I noticed game-shell was a tad more careful about some browser differences, e.g. https://caniuse.com/?search=exitFullscreen which is prefixed on iOS safari - it may be worth being careful here e.g.
```
var cancelFullscreen = document.exitFullscreen ||
                       document.cancelFullscreen ||  //Why can no one agree on this?
                       document.cancelFullScreen ||
                       document.webkitCancelFullscreen ||
                       document.webkitCancelFullScreen ||
                       document.mozCancelFullscreen ||
                       document.mozCancelFullScreen ||
                       function(){}
```
as in game-shell (though I'm sure not all of these are necessary, cross-browser compatibility with these APIs has improved over the years)

**Comment by fenomas** [comment]
Hi, thanks for the info!

Can certainly change the tick stuff, but let me be sure I understand the use case. 

My reasoning here was: normally we expect tick to run less frequently than render (otherwise there's no reason to separate the two). So if the game is in a state where multiple ticks are pending, then that probably means that things are CPU-bound and doing multiple ticks would just put the game even further behind than it already is.

Are you talking about a situation where the refresh rate is lower than the tick rate for reasons other than CPU? E.g. because the browser is throttling RAF, or because the game is just intentionally rendering at a slow rate? Or do you mean situations where the game is CPU-bound but you want it to try more aggressively to catch up?

**Comment by MCArth** [comment]
I think the biggest use case for this is for when tick lengths can vary - I definitely have kinks to iron out but I added in some logging, and had this result over ~10 seconds
![image](https://user-images.githubusercontent.com/26874892/131254617-8d85db74-3594-41ee-9bad-bb7def914170.png)
The number is the ms skipped forwards. 

Even if the client is completely CPU bound on a multiplayer game, it may be worth trying harder to catch up - to prevent desync with the server.

**Comment by fenomas** [comment]
Hi, sorry I haven't gotten to this yet but I agree that it makes sense for it to be tunable! I will add this when I have it open next, although there have been no recent changes to `noa`, so it might be a while before the change makes it out of the develop branch.

**Comment by MCArth** [comment]
I've landed on using something like the following:

```
function intervalHandler(shell) {
    var tickDur = 1000 / shell.tickRate

    // The time we'll stop ticking at if past.
    // Prevents too much time passing without a new frame.
    var tickTill = shell._nowObject.now() + (tickDur+5)*1.5

    while (shell._nowObject.now() >= shell._lastTick + tickDur && shell._nowObject.now() < tickTill) {
        shell.onTick(tickDur)
        shell._lastTick += tickDur
    }

    // If we're too far behind, skip ahead.
    var now = shell._nowObject.now()
    if (now-shell._lastTick > (tickDur+5)*5) {
        while (now >= shell._lastTick+tickDur) {
            shell._lastTick += tickDur
        }
    }
}
```

I found that if I didn't ever allow more than one tick to go at once at low frame rates I had this weird prediction thing where it felt like I teleported back and forth a bit; not sure of the root cause, possibly something happening in noa. Allowing too many ticks to go at once like game-shell did, of course means you have large stutters!

Not sure if this will be useful (I understand you're making a single player game), but hopefully it helps 😄

**Comment by fenomas** [comment]
Hi, thanks for the feedback here. I pushed a change (here, not to npm yet) that uses a fixed cutoff time, like game-shell, defaulting to 100ms. That is, it will tick multiple times to catch up, but if one batch of ticks takes more than 100ms it will skip frames. I tried a couple other options, but this approach seemed to give the smoothest results in the test page, for realistic cases where the tick function is (temporarily) too slow.

Please have a look if you like!

(edit: actually I went ahead and published this to npm)

**Comment by MCArth** [comment]
Looking good, thanks for taking action! I agree going based on a flat MS makes sense. In case it's helpful - I also ended up making a change to my branch of noa which meant meshing only gets attempted once every few ticks - which reduced the chance you'd end up with multiple large ticks next to each other and seemed to make the game smoother when new sections of a world.

Out of interest, it sounds like you don't expect the game to be CPU bound. On higher end devices, this is the case for me, while on lower end devices I'm CPU bound simply by babylon's on render cpu work. Have you not found that to be the case? It seems like the amount of work done by RenderingManager.render starts off at quite a high amount (with below 60fps on low-end machines), but scales very slowly with number of meshes/chunkAddDistance.

for instance, in a relatively flat world, on my high end machine there seems to be ~3ms worth of work to do with blockadddistance of 1 (about half in RenderingManager.render) and only ~11ms with blockAddDistance of 10! These numbers seem to scale up proportionately on my low end testing machine.

have you found different results? My takeaway before this thread was there was a baseline amount of work needed to do, no matter what

**Comment by fenomas** [comment]
No, I've definitely found everything is always CPU-bound, occasionally on noa's side (during thrash when meshing lots and lots of new chunks), but in the steady state in Babylon. But I think for most games, once CPU is harshly limiting things that will probably happen more in renders than in ticks, so this lib sort of makes that assumption. 

For Babylon, I haven't profiled heavily recently, but what you're saying sounds about right. At very large view distances it starts spending a lot of time on mesh selection, which I try to mitigate with octrees. OTOH I'm not sure about the baseline amount of work being done even for small scenes... however I haven't done any testing on low-end hardware. Do you mean mobile, or non-gaming PCs, or the like?

**Comment by MCArth** [comment]
Ok, makes sense. Yep, I've been doing some testing on my mobile and a cheap chromebook. Thanks for the info!
