### ISSUE TITLE
requestPointerLock is not a function on safari iOS

### ISSUE THREAD

**Issue by MCArth** [fenomas/micro-game-shell#2]
Hi, it turns out safari on iPhone iOS doesn't support the requestPointerLock api, which causes a crash.

![image](https://user-images.githubusercontent.com/26874892/148112980-f4c8259f-a65b-47bb-ac2f-b8ba1c7b4da8.png)

This is a pretty simple fix of checking whether the property exists, but it caught me out as I don't have an iPhone for testing

**Comment by fenomas** [comment]
Thanks, fixed!
