### ISSUE TITLE
requestPointerLock does not reliably return a promise

### ISSUE THREAD

**Issue by roboticdemonowl** [fenomas/micro-game-shell#3]
```javascript
var prom = el.requestPointerLock()
if (prom.catch) prom.catch(err => {
    if (shell.onPointerLockerror) shell.onPointerLockerror(err)
})
```

According to [mdn](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestPointerLock), requestPointerLock does not reliably return a promise. Officially, it's supposed to return undefined. The promise is only returned in Chromium because of their proposed specification change (click on the asterisk under Chrome in the browser compatibility table for details).

In Safari, the code throws an error since prom is undefined (TypeError: undefined is not an object (evaluating 'prom.catch')). I believe the proper way to handle pointer lock errors in non-Chromium browsers is to listen for pointerlockerror events at the Document level.

**Comment by fenomas** [comment]
Nice catch, thanks! I'll push a fix for this. (and also fix the camelCase in `onPointerLockError`)
